


# Docker Compose file version
version: '3.8'

services:
  # Hadoop NameNode service
  namenode:
    image: bde2020/hadoop-namenode:2.0.0-hadoop2.7.4-java8
    container_name: namenode
    environment:
      - CLUSTER_NAME=test  # Set the cluster name
    ports:
      - "50070:50070"  # NameNode web UI
      - "9000:9000"    # NameNode RPC
      - "9870:9870"    # NameNode webhdfs
    networks:
      net_pet:
        ipv4_address: 172.27.1.5  # Static IP address

  # Hadoop DataNode service
  datanode:
    image: bde2020/hadoop-datanode:2.0.0-hadoop2.7.4-java8
    container_name: datanode
    volumes:
      - /tmp/hdfs/datanode:/hadoop/dfs/data  # Mount volume for DataNode data
    environment:
      SERVICE_PRECONDITION: "namenode:50070"  # Ensure NameNode is running
    depends_on:
      - namenode  # Start NameNode first
    ports:
      - "50075:50075"  # DataNode web UI
      - "9864:9864"    # DataNode service
    networks:
      net_pet:
        ipv4_address: 172.27.1.6  # Static IP address

  # Spark Master service
  spark-master:
    image: bde2020/spark-master:2.4.0-hadoop2.7
    container_name: spark-master
    ports:
      - "8080:8080"  # Spark Master web UI
      - "7077:7077"  # Spark Master service
    environment:
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020  # HDFS configuration
    networks:
      net_pet:
        ipv4_address: 172.27.1.10  # Static IP address

  # Spark Worker service
  spark-worker:
    image: bde2020/spark-worker:2.4.0-hadoop2.7
    container_name: spark-worker
    depends_on:
      - spark-master  # Start Spark Master first
    environment:
      - SPARK_MASTER=spark://spark-master:7077  # Spark Master URL
      - CORE_CONF_fs_defaultFS=hdfs://namenode:8020  # HDFS configuration
    ports:
      - "8081:8081"  # Spark Worker web UI
    networks:
      net_pet:
        ipv4_address: 172.27.1.11  # Static IP address

# Define the custom network
networks:
  net_pet:
    ipam:
      driver: default
      config:
        - subnet: 172.27.0.0/16  # Custom subnet for the network





